<style>
    .container-middle, .section-item{ margin: auto; }
</style>
<div class="prmo-mail">
    <table width="100%" cellspacing="0" cellpadding="0" border="0">
        <tbody><tr><td height="30"></td></tr>
            <tr bgcolor="#43B74A">
                <td width="100%" valign="top" bgcolor="#4c4e4e" align="center">

                    <!---------   top header   ------------>
                    <table width="600" cellspacing="0" cellpadding="0" border="0" align="center" class="container">
                        <tbody>
			    <tr  bgcolor="#43B74A" style='border-radius:5px 5px 0 0;' >
                                <td>&nbsp;</td>
                            </tr>
                            <tr bgcolor="#43B74A">
				<td height="5"></td>
			    </tr>
                            <tr bgcolor="#43B74A">
                                <td align="center">
                                    <table width="560" cellspacing="0" cellpadding="0" border="0" align="center" class="container-middle" style='margin:0 auto;' >
                                        <tbody><tr>
                                                <td>
                                                    <table cellspacing="0" cellpadding="0" border="0" align="left" class="top-header-left">
                                                        <tbody><tr>
                                                                <td align="center">
                                                                    <table cellspacing="0" cellpadding="0" border="0" class="date">
                                                                        <tbody><tr>
                                                                                <td>
                                                                                    <img width="13" alt="icon 1" src="http://promailthemes.com/campaigner/layout1/white/blue/img/icon-cal.png" style="display: block;" mc:edit="icon1" editable="true">
                                                                                </td>
                                                                                <td>&nbsp;&nbsp;</td>
                                                                                <td style="color: #fefefe; font-size: 11px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" mc:edit="date">
                                                                        <singleline>
                                                                            DATE
                                                                        </singleline>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                </td>
                                            </tr>
                                        </tbody></table>

                                    <table cellspacing="0" cellpadding="0" border="0" align="left" class="top-header-right">
                                        <tbody><tr><td width="30" height="20"></td></tr>
                                        </tbody></table>

                                   
                </td>
            </tr>
        </tbody></table>
</td>
</tr>

<tr bgcolor="#43B74A"><td height="10"></td></tr>

</tbody></table>

<!----------    end top header    ------------>


<!----------   main content----------->
<table width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="ececec" align="center" class="container">


    <!--------- Header  ---------->
    <tbody><tr bgcolor="ececec"><td height="40"></td></tr>

        <tr>
            <td>
                <table width="560" cellspacing="0" cellpadding="0" border="0" align="center" class="container-middle">
                    <tbody><tr>
                            <td>
                                <table cellspacing="0" cellpadding="0" border="0" align="left" class="logo">
                                    <tbody><tr>
                                            <td align="center">
                                                CULOGO
                                            </td>
                                        </tr>
                                    </tbody></table>		
                                <table cellspacing="0" cellpadding="0" border="0" align="left" class="nav">
                                    <tbody><tr>
                                            <td width="20" height="20"></td>
                                        </tr>
                                    </tbody></table>
                                
            </td>
        </tr>
    </tbody></table>
</td>
</tr>

<tr bgcolor="ececec"><td height="40"></td></tr>
<!---------- end header --------->


<!--------- main section --------->                	
<tr>
    <td>
        <table width="560" cellspacing="0" cellpadding="0" border="0" align="center" class="container-middle">

            <tbody><tr><td align="center"><img width="560" height="auto" class="top-bottom-bg" alt="" src="http://promailthemes.com/campaigner/layout1/white/blue/img/top-rounded-bg.png" style="display: block;"></td></tr>

                <tr bgcolor="#ffffff"><td height="7"></td></tr>


                <tr bgcolor="#ffffff"><td height="20"></td></tr>

                <tr bgcolor="#ffffff">
                    <td>
                        <table width="100%" cellspacing="0" cellpadding="0" border="0" align="center" class="mainContent" style='padding:0 15px' >
                            <tbody><tr>	
                                    <td style="color: #484848; font-size: 16px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" class="main-header" mc:edit="title1">
                            <multiline>
                               <p>Hi FIRSTNAME<br />
Thank you for your shown interest in the products that you have put into Your cart at <a href="http://projects.udaantechnologies.com/magentodev">www.projects.udaantechnologies.com</a></p>

<p>We noticed that you left the cart for XDAYSFROMSETTINGS days and just like to offer you this extra service.</p>

<p>We work with <a href="http://Pricelizer.com" target="_blank">Pricelizer.com</a> that offers automatic price alerts when the products already chosen by you drop in price.</p>

<p>Do you want to receive email alerts when we change the price on the product(s) in your cart?<br />
Then simply with a single mouse click on any of the listed buttons using your preferred social media account we will create an account and have the products added without you having to think a second more about this,preferred social media account we will create an account and have the products added without you having to think a second more about this,</p>

<p>Click on social media icon to create a price alert account: .</p>

<p>1CLICKSIGNUP</p>


<p>Just wait and see as the price drop</p>

<p>Best regards<br />
<a href="http://projects.udaantechnologies.com/magentodev" target="_blank">www.projects.udaantechnologies.com</a></p>

                            </multiline>
                    </td>
                </tr>
               
</tbody></table>
</td>
</tr>

<tr bgcolor="ffffff"><td height="25"></td></tr>

<tr><td align="center"><img width="560" height="auto" class="top-bottom-bg" alt="" src="http://promailthemes.com/campaigner/layout1/white/blue/img/bottom-rounded-bg.png" style="display: block;"></td></tr>	

</tbody></table>
</td>
</tr><!--------- end main section --------->


<tr><td height="35"></td></tr>





<!---------- prefooter  --------->

<tr>
    <td>
        <table width="560" cellspacing="0" cellpadding="0" border="0" align="center" class="container-middle">
            <tbody><tr>
                    <td>
                        <table cellspacing="0" cellpadding="0" border="0" align="left" class="logo">
                            <tbody><tr>
                                    <td align="center">
                                        <span style='float:left;'>PRICELIZERLOGO </span><span style='color: #989898; margin-left: 10px; float:left; line-height:79px;'>FLINK</span>
                                    </td>
                                </tr>
                                
                               
                            </tbody></table>		
                        <table cellspacing="0" cellpadding="0" border="0" align="left">
                            <tbody><tr>
                                    <td width="20" height="20"></td>
                                </tr>
                            </tbody></table>
                        <table cellspacing="0" cellpadding="0" border="0" align="right" class="nav">
                            <tbody><tr><td height="10"></td></tr>
                                <tr>
                                    <td align="center" style="font-size: 13px; font-family: Helvetica, Arial, sans-serif;" mc:edit="socials">
                                      
                                    </td>
                                </tr>
                            </tbody></table>
                    </td>
                </tr>
            </tbody></table>
    </td>
</tr><!---------- end prefooter  --------->

<tr><td height="40"></td></tr>
<tr>
    <td align="center" class="prefooter-header" style="color: #939393; font-size: 11px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" mc:edit="copy1">
<multiline>
    You are currently signed up as: <span style="color: #2f90e2">email@email.com</span> to unsubscribe  UNCLICK
</multiline>
</td>
</tr>	

<tr><td height="30"></td></tr>

<tr>
    <td align="center" class="prefooter-subheader" style="color: #939393; font-size: 11px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" mc:edit="copy2">

</td>
</tr>

<tr><td height="30"></td></tr>
</tbody></table>
<!------------ end main Content ----------------->


<!---------- footer  --------->
<table width="600" cellspacing="0" cellpadding="0" border="0" class="container" align="center">
    <tbody><tr bgcolor="#43B74A"><td height="14"></td></tr>
        <tr bgcolor="#43B74A">
            <td align="center" style="color: #fff; font-size: 10px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" mc:edit="copy3">
    <multiline>
         &copy; 2015 FIRSTNAME, Inc.
    </multiline>
    </td>
    </tr>

    <tr  bgcolor="#43B74A" style="" >
        <td>&nbsp;</td>
    </tr>
    </tbody></table>
<!---------  end footer --------->
</td>
</tr>

<tr><td height="30"></td></tr>

</tbody></table>
</div>
