<style>
    .cont-mang {
  float: left;
  padding: 0 20px;
  width: 97%;
}
    table.data{ width: 100%; }
    .grid h1.title-name{font-size:14px; text-transform:capitalize; float:left;margin-right:10px;}
    .invite_link{font-weight:bold; text-decoration:none;}
    .invite_link{font-weight:bold; text-decoration:underline;}
    a.price_alert {
	background: #EA7601;
	color: #FFFFFF;   
	margin-bottom: 10px;
	padding: 5px 10px;
	text-align: right;
	text-decoration: none; border-radius:5px;
    }
    a.price_alert:hover{color: #FFFFFF; background:orange;} 
    .email_send{color:#66a202;}
    .email_not_send{color:#ff0000;}
    table.data td{font-size:0.9em;}
/*    .cont-mang{
	width: 100%;
	float: left;
    }*/
    .data input[type="text"]{
	width: 80%;
    }
    .grid {
	float: left;
	width: 100%;
    }
    .app-title-name{text-align:center; padding:10px; font-size:24px; color:#eb5e00;}

    .click-price{width:100%; height:30px; text-align:center;}

    .setting-from{ width:250px; margin:0px auto; height:50px;}
    .setting-from .man{ width:100px; float:left; font-size:14px;}
    .setting-from .auto{ width:100px; float:left; font-size:14px;}
    .form_content {
	border: 1px solid #EB5E00;
	box-shadow: 0 0 3px #DDDDDD;
	margin: 0 auto;
	padding: 30px;
	text-align: center;

    }
    .form_content input {
	height: 40px;
	margin-bottom: 10px;
	width: 100%;
	padding:10px;
    }
    .form_content button {
	padding:10px;
    }
    .align_center{
	margin:0 auto;
	width:30%;
	margin-top:90px;
	text-align:center;

    }
    .align_center h2{
	color:#EB5E00;
    }
    .setting-from .man {
	float: left;
	font-size: 14px;
	width: 100%;
    }
    .setting-from .auto {
	float: left;
	font-size: 14px;
	font-weight: bold;
	margin-top: 4px;
	width: auto;
    }
    .setting-from {
	height: 50px;
	margin: 0 auto;
	width: 310px;
    }
    .man > h3 {
	float: left;
    }
    .btn_manage{
	text-align:center;
    }
    .btn_manage select{
	width:200px;
	height:20px;
	margin-bottom:5px;
    }
    .btn_align{
	text-align:center;
    }
</style>
<style type="text/css">
    .white_content {
	background-color: #ffffff;
	border: 5px solid ;
	height: 50%;
	left: 25%;
	max-height: 500px;
	overflow: auto;
	padding: 13px 15px;
	position: fixed;
	top: 20%;
	width: 50%;
	z-index: 1008; 
	display:none;
    }
    .close-btn
    {
	font-size:20px;
	float:right;
    }


    .pagination {
	border-radius: 4px;
	display: inline-block;
	margin: 0px;
	padding-left: 0;
    }
    .pagination > li {
	display: inline;
    }

    .pagination > li:first-child > a, .pagination > li:first-child > span {
	border-bottom-left-radius: 4px;
	border-top-left-radius: 4px;
	margin-left: 0;
    }

    .pagination > li, .pagination > li > span {
	background-color: #fff;
	border: 1px solid #ddd;
	color: #428bca;
	float: left;
	line-height: 1.42857;
	margin-left: -1px;
	padding: 6px 12px;
	position: relative;
	text-decoration: none;
    }


    .page{ background-color: #fff;
	  border: none;
	  color: #000;
	  float: left;
	  line-height: 1.42857;
	  margin-left: -1px;
	  padding: 6px 12px;
	  position: relative;
	  text-decoration: none;
    }
    .centrick{width:275px; margin:0px auto;} 
    .centrick:after{clear:both;}    
    .catched-user-tracker .checkbox, .one-click-signup .checkbox, .add-watchlist-button .checkbox{ margin-bottom: 5px; }
    .catched-user-tracker label, .one-click-signup label, .add-watchlist-button label, .checkbox label{ margin:0 6px; }
   .catched-user-tracker input, .catched-user-tracker select { margin-bottom: 3px; margin-right: 2px; vertical-align: middle; }
   .one-click-signup input, .one-click-signup select { margin-bottom: 3px; margin-right: 4px; vertical-align: middle; }
   .add-watchlist-button input, .add-watchlist-button select { margin-bottom: 3px; margin-right: 4px; vertical-align: middle; }
   .border-bottm{ border-bottom: 1px solid #ccc; padding-bottom: 10px; margin-bottom: 15px; }
   .inner-content{ padding: 0 30px; }
   .checkbox{margin-bottom:5px;}
   button#catched_setting, button#save_signup, button#save_watchlist, #logo_setting, #link_setting { margin-left: 7px; }
   .text-success{ padding-left: 7px; margin-top: 5px; color: #3c763d; }
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>jQuery.noConflict();</script> 
<?php
	echo '<div class="content-header">
			 <h3 class="icon-head head-report-shopcart-abandoned">Non registered user statistics</h3>				
			</div>';
require_once 'app/Mage.php';

/*
 * Initialize Magento. Older versions may require Mage::app() instead.
 */
 ?>
 
 <!------------------- Total Number of users------------------------------------------>
		<?php
		
		$read_user = Mage::getSingleton('core/resource')->getConnection('core_read') ;
		$write_user = Mage::getSingleton('core/resource')->getConnection('core_write'); 
		$result_user_count = $read_user->fetchAll("SELECT * FROM Abandon_cart_users"); 
		 $result_user_count['0']['Abandoned_cart'];
		 $result_user_count['0']['Catched_user'];
        $trace_user_ip = $read_user->fetchAll("SELECT * FROM abandoned_user_ip WHERE pay_status='pending'");
        foreach($trace_user_ip as $uip)
        {
			//echo '<pre>';print_r($uip);
			
			
		

	//echo '<pre>';print_r($order);
	echo '<div class="grid"><div class="hor-scroll"><table border="1px solid">';
   
	echo '<tr class="headings"><td colspan="11">'.$strip_date.'</td></tr>';
	echo '<tr class="headings"><th>Product Name</th><th>Price</th><th>Pay status</th><th>Customer Email</th><th>Customer IP</th><th>Added date</th></tr>';
    foreach($trace_user_ip as $uip){
		//echo '<pre>';print_r($item);
		
	echo '<td>'.$uip['product_name'].'</td>';
	echo '<td>'.$uip['Product_price'].'</td>'; 
	echo '<td>'.$uip['pay_status'].'</td>';
	echo '<td>'.$uip['email_id'].'</td>';
	
	echo '<td>'.$uip['user_ip'].'</td>';
	echo '<td>'.$uip['added_date'].'</td></tr>';
	
   
    }
    
    echo '<tr></tr>';
    echo '</table></div></div>';
    
 
    
}






?>
